# Generated by Django 5.2.15 on 2026-06-24 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eligibility', '0005_eligibilityresponse_questionnaire_responses_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FunnelEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(db_index=True, max_length=64)),
                ('questionnaire_slug', models.CharField(blank=True, default='', max_length=32)),
                ('questionnaire_version_id', models.UUIDField(blank=True, null=True)),
                ('step_key', models.CharField(blank=True, default='', max_length=64)),
                ('experiment_id', models.UUIDField(blank=True, null=True)),
                ('variant_key', models.CharField(blank=True, default='', max_length=32)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('funnel_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnel_events', to='eligibility.funnelsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnel_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'funnel_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['questionnaire_slug', 'step_key', 'created_at'], name='funnel_even_questio_a5bc94_idx'), models.Index(fields=['experiment_id', 'variant_key'], name='funnel_even_experim_3a7e6d_idx')],
            },
        ),
    ]
