# Generated by Django 5.2.15 on 2026-06-25 18:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('headline', models.CharField(blank=True, default='', max_length=256)),
                ('subheadline', models.CharField(blank=True, default='', max_length=512)),
                ('utm_source', models.CharField(blank=True, default='', max_length=128)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=128)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=128)),
                ('utm_content', models.CharField(blank=True, default='', max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'landing_pages',
                'ordering': ['-created_at'],
            },
        ),
    ]
