# Generated by Django 5.2.15 on 2026-06-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_add_landing_page_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='redirect_to_home',
            field=models.BooleanField(default=False),
        ),
    ]
