from django.urls import path

from apps.questionnaires.staff_views import (
    StaffApiVendorDetailView,
    StaffApiVendorListView,
    StaffApiVendorVersionArchiveView,
    StaffApiVendorVersionDetailView,
    StaffApiVendorVersionListView,
    StaffApiVendorVersionPublishView,
    StaffApiVendorVersionUnarchiveView,
    StaffMedicationDetailView,
    StaffMedicationListView,
    StaffQualifyCtaOwnershipView,
    StaffQuestionnaireArchiveView,
    StaffQuestionnaireDetailView,
    StaffQuestionnaireDuplicateQuestionnaireView,
    StaffQuestionnaireDuplicateView,
    StaffQuestionnaireVersionExportView,
    StaffQuestionnaireVersionImportView,
    StaffQuestionnaireFieldDetailView,
    StaffQuestionnaireFieldListView,
    StaffQuestionnaireListView,
    StaffQuestionnairePublishView,
    StaffQuestionnaireStepDetailView,
    StaffQuestionnaireStepListView,
    StaffQuestionnaireVersionDetailView,
    StaffQuestionnaireVersionListView,
)

vendor_urlpatterns = [
    path("", StaffApiVendorListView.as_view(), name="staff-vendor-list"),
    path(
        "<uuid:vendor_id>/",
        StaffApiVendorDetailView.as_view(),
        name="staff-vendor-detail",
    ),
    path(
        "<uuid:vendor_id>/versions/",
        StaffApiVendorVersionListView.as_view(),
        name="staff-vendor-version-list",
    ),
    path(
        "<uuid:vendor_id>/versions/<uuid:version_id>/",
        StaffApiVendorVersionDetailView.as_view(),
        name="staff-vendor-version-detail",
    ),
    path(
        "<uuid:vendor_id>/versions/<uuid:version_id>/publish/",
        StaffApiVendorVersionPublishView.as_view(),
        name="staff-vendor-version-publish",
    ),
    path(
        "<uuid:vendor_id>/versions/<uuid:version_id>/archive/",
        StaffApiVendorVersionArchiveView.as_view(),
        name="staff-vendor-version-archive",
    ),
    path(
        "<uuid:vendor_id>/versions/<uuid:version_id>/unarchive/",
        StaffApiVendorVersionUnarchiveView.as_view(),
        name="staff-vendor-version-unarchive",
    ),
]

medication_urlpatterns = [
    path("", StaffMedicationListView.as_view(), name="staff-medication-list"),
    path(
        "<uuid:medication_id>/",
        StaffMedicationDetailView.as_view(),
        name="staff-medication-detail",
    ),
]

urlpatterns = [
    path("", StaffQuestionnaireListView.as_view(), name="staff-questionnaire-list"),
    path(
        "qualify-cta-ownership/",
        StaffQualifyCtaOwnershipView.as_view(),
        name="staff-qualify-cta-ownership",
    ),
    path(
        "<slug:slug>/",
        StaffQuestionnaireDetailView.as_view(),
        name="staff-questionnaire-detail",
    ),
    path(
        "<slug:slug>/duplicate/",
        StaffQuestionnaireDuplicateQuestionnaireView.as_view(),
        name="staff-questionnaire-duplicate-questionnaire",
    ),
    path(
        "<slug:slug>/versions/",
        StaffQuestionnaireVersionListView.as_view(),
        name="staff-questionnaire-versions",
    ),
    path(
        "<slug:slug>/versions/import/",
        StaffQuestionnaireVersionImportView.as_view(),
        name="staff-questionnaire-version-import",
    ),
    path(
        "<slug:slug>/versions/<uuid:version_id>/",
        StaffQuestionnaireVersionDetailView.as_view(),
        name="staff-questionnaire-version-detail",
    ),
    path(
        "<slug:slug>/versions/<uuid:version_id>/export/",
        StaffQuestionnaireVersionExportView.as_view(),
        name="staff-questionnaire-version-export",
    ),
    path(
        "<slug:slug>/versions/<uuid:version_id>/publish/",
        StaffQuestionnairePublishView.as_view(),
        name="staff-questionnaire-publish",
    ),
    path(
        "<slug:slug>/versions/<uuid:version_id>/archive/",
        StaffQuestionnaireArchiveView.as_view(),
        name="staff-questionnaire-archive",
    ),
    path(
        "<slug:slug>/versions/<uuid:version_id>/duplicate/",
        StaffQuestionnaireDuplicateView.as_view(),
        name="staff-questionnaire-duplicate",
    ),
    path(
        "<slug:slug>/versions/<uuid:version_id>/steps/",
        StaffQuestionnaireStepListView.as_view(),
        name="staff-questionnaire-step-create",
    ),
    path(
        "<slug:slug>/versions/<uuid:version_id>/steps/<str:step_key>/",
        StaffQuestionnaireStepDetailView.as_view(),
        name="staff-questionnaire-step-detail",
    ),
    path(
        "<slug:slug>/versions/<uuid:version_id>/steps/<str:step_key>/fields/",
        StaffQuestionnaireFieldListView.as_view(),
        name="staff-questionnaire-field-create",
    ),
    path(
        "<slug:slug>/versions/<uuid:version_id>/steps/<str:step_key>/fields/<str:field_key>/",
        StaffQuestionnaireFieldDetailView.as_view(),
        name="staff-questionnaire-field-detail",
    ),
]
