// @lovable.dev/vite-tanstack-config already includes the following — do NOT add them manually
// or the app will break with duplicate plugins:
//   - tanstackStart, viteReact, tailwindcss, tsConfigPaths, nitro (build-only using cloudflare as a default target),
//     componentTagger (dev-only), VITE_* env injection, @ path alias, React/TanStack dedupe,
//     error logger plugins, and sandbox detection (port/host/strictPort).
// You can pass additional config via defineConfig({ vite: { ... }, etc... }) if needed.
import { defineConfig } from "@lovable.dev/vite-tanstack-config";

export default defineConfig({
  tanstackStart: {
    // Redirect TanStack Start's bundled server entry to src/server.ts (our SSR error wrapper).
    // nitro/vite builds from this
    server: { entry: "server" },
    // Static export for GitHub Pages (beemahealth)
    spa: {
      enabled: true,
      // The SPA shell (_shell.html) is generated by prerendering maskPath
      // with its content masked — that path loses its real prerender. The
      // default maskPath is "/", which shipped an EMPTY homepage to
      // crawlers. Use /dashboard: client-only, auth-gated, robots-blocked.
      maskPath: "/dashboard",
    },
    prerender: {
      enabled: true,
      filter: ({ path }) =>
        // Exact /dashboard is the spa.maskPath shell entry — it must pass
        // the filter to emit _shell.html (it never writes dashboard HTML).
        path === "/dashboard" ||
        !["/dashboard", "/intake", "/consent", "/verify-email/pending"].some(
          (prefix) => path === prefix || path.startsWith(`${prefix}/`),
        ),
    },
    client: { base: "/" },
  },
  vite: {
    base: "/",
    server: {
      // Same-origin proxy so HttpOnly funnel cookies (beemahealth_funnel) persist in dev.
      // Frontend :8080 → /api/* → backend :8000/api/*
      proxy: {
        "/api": {
          target: "http://localhost:8000",
          changeOrigin: true,
        },
      },
    },
  },
});
