# Generated by Django 5.2.15 on 2026-06-16 02:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('height_ft', models.CharField(max_length=8)),
                ('height_in', models.CharField(blank=True, default='0', max_length=8)),
                ('weight', models.CharField(max_length=8)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('goal_weight', models.CharField(max_length=8)),
                ('biological_sex', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=16)),
                ('is_adult', models.BooleanField()),
                ('lives_in_colorado', models.BooleanField()),
                ('located_in_colorado', models.BooleanField()),
                ('city', models.CharField(max_length=128)),
                ('zip_code', models.CharField(max_length=16)),
                ('treatment_interest', models.CharField(choices=[('insurance_brand', 'Insurance brand'), ('cash_pay', 'Cash pay'), ('not_sure', 'Not sure')], max_length=32)),
                ('injection_preference', models.CharField(choices=[('yes', 'Yes'), ('pill_preferred', 'Pill preferred'), ('not_sure', 'Not sure')], max_length=32)),
                ('budget', models.CharField(choices=[('under_200', 'Under $200'), ('200_300', '$200–$300'), ('300_500', '$300–$500'), ('500_plus', '$500+'), ('insurance', 'Insurance')], max_length=32)),
                ('safety_screen', models.JSONField(default=dict)),
                ('safety_concern_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eligibility_responses',
            },
        ),
    ]
