# Generated by Django 5.2.15 on 2026-06-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0002_funnel_session_schema_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilityresponse',
            name='safety_screen',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
