# Generated by Django 5.2.15 on 2026-06-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0004_eligibilityresponse_gender_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilityresponse',
            name='questionnaire_responses',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='eligibilityresponse',
            name='questionnaire_version_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funnelsession',
            name='experiment_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funnelsession',
            name='qualify_questionnaire_version_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funnelsession',
            name='utm_campaign',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='funnelsession',
            name='utm_content',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='funnelsession',
            name='utm_medium',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='funnelsession',
            name='utm_source',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='funnelsession',
            name='variant_key',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
