# Generated by Django 5.2.15 on 2026-06-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0005_eligibilityresponse_questionnaire_responses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funnelsession',
            name='landing_page_slug',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
