# Generated by Django 5.2.15 on 2026-06-16 02:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalIntake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('more_info_needed', 'More information needed'), ('approved', 'Approved'), ('not_approved', 'Not approved'), ('prescription_sent', 'Prescription sent')], default='draft', max_length=32)),
                ('identity', models.JSONField(default=dict)),
                ('body_metrics', models.JSONField(default=dict)),
                ('weight_history', models.JSONField(default=dict)),
                ('medical_conditions', models.JSONField(default=dict)),
                ('family_history', models.JSONField(default=dict)),
                ('medications', models.JSONField(default=dict)),
                ('allergies', models.JSONField(default=dict)),
                ('pregnancy', models.JSONField(default=dict)),
                ('lifestyle', models.JSONField(default=dict)),
                ('labs', models.JSONField(default=dict)),
                ('medication_preferences', models.JSONField(default=dict)),
                ('safety_acknowledgments', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medical_intakes',
            },
        ),
        migrations.CreateModel(
            name='SafetyFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag_type', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safety_flags',
                'ordering': ['-created_at'],
            },
        ),
    ]
