# Generated by Django 5.2.15 on 2026-06-19 15:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_submissions(apps, schema_editor):
    MedicalIntake = apps.get_model("intakes", "MedicalIntake")
    IntakeSubmission = apps.get_model("intakes", "IntakeSubmission")

    submitted_statuses = [
        "submitted",
        "under_review",
        "more_info_needed",
        "approved",
        "not_approved",
        "prescription_sent",
    ]
    for intake in MedicalIntake.objects.filter(status__in=submitted_statuses):
        if IntakeSubmission.objects.filter(medical_intake=intake).exists():
            continue
        user = intake.user
        submitted_at = intake.submitted_at
        if submitted_at is None:
            from django.utils import timezone

            submitted_at = timezone.now()
        snapshot = {
            "meta": {
                "version": 1,
                "submitted_at": submitted_at.isoformat() if submitted_at else None,
                "intake_id": str(intake.id),
                "intake_status": intake.status,
            },
            "account": {
                "first_name": user.first_name,
                "last_name": user.last_name,
                "email": user.email,
                "phone": user.phone or "",
                "dob": user.dob.isoformat() if user.dob else "",
                "state": user.state or "",
            },
            "clinical": {
                "identity": intake.identity or {},
                "body_metrics": intake.body_metrics or {},
                "weight_history": intake.weight_history or {},
                "medical_conditions": intake.medical_conditions or {},
                "family_history": intake.family_history or {},
                "medications": intake.medications or {},
                "allergies": intake.allergies or {},
                "pregnancy": intake.pregnancy or {},
                "lifestyle": intake.lifestyle or {},
                "labs": intake.labs or {},
                "medication_preferences": intake.medication_preferences or {},
                "safety_acknowledgments": intake.safety_acknowledgments or {},
            },
        }
        IntakeSubmission.objects.create(
            user=user,
            medical_intake=intake,
            version=1,
            status_at_submit="submitted",
            snapshot=snapshot,
            submitted_at=submitted_at,
        )
        intake.active_submission_version = 1
        intake.working_version = 1
        intake.save(update_fields=["active_submission_version", "working_version"])


class Migration(migrations.Migration):

    dependencies = [
        ("intakes", "0003_refillrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalintake',
            name='active_submission_version',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalintake',
            name='working_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='IntakeSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveSmallIntegerField()),
                ('status_at_submit', models.CharField(choices=[('submitted', 'Submitted'), ('resubmitted', 'Resubmitted')], default='submitted', max_length=32)),
                ('snapshot', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='intakes.medicalintake')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intake_submissions',
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('user', 'version'), name='unique_intake_submission_version')],
            },
        ),
        migrations.RunPython(backfill_submissions, migrations.RunPython.noop),
    ]
