# Generated by Django 5.2.15 on 2026-06-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intakes', '0006_backfill_submission_identity_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakesubmission',
            name='questionnaire_version_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalintake',
            name='questionnaire_responses',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='medicalintake',
            name='questionnaire_version_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
