# Generated by Django 5.2.15 on 2026-07-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intakes', '0009_refill_titration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='refillrequest',
            name='beluga_order_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
