# Generated by Django 5.2.15 on 2026-07-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intakes', '0010_refillrequest_beluga_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refillrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('more_info_needed', 'More information needed')], default='pending', max_length=16),
        ),
    ]
