# Generated by Django 5.2.15 on 2026-06-16 02:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telehealth_consent', models.BooleanField()),
                ('no_guarantee_acknowledgment', models.BooleanField()),
                ('emergency_disclaimer_acknowledgment', models.BooleanField()),
                ('medication_risk_acknowledgment', models.BooleanField()),
                ('compounded_medication_acknowledgment', models.BooleanField()),
                ('privacy_acknowledgment', models.BooleanField()),
                ('typed_signature', models.CharField(max_length=255)),
                ('signed_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consent_records',
            },
        ),
    ]
