# Generated by Django 5.2.15 on 2026-06-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patientprofile_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='county',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
