# Generated by Django 5.2.15 on 2026-06-24 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(choices=[('qualify', 'Qualify'), ('intake', 'Intake')], max_length=32, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'questionnaires',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('stopped', 'Stopped'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiments_created', to=settings.AUTH_USER_MODEL)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='questionnaires.questionnaire')),
            ],
            options={
                'db_table': 'experiments',
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_label', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire_versions_created', to=settings.AUTH_USER_MODEL)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='questionnaires.questionnaire')),
            ],
            options={
                'db_table': 'questionnaire_versions',
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_key', models.CharField(max_length=64)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=256)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('visibility_rule', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='questionnaires.questionnaireversion')),
            ],
            options={
                'db_table': 'questionnaire_steps',
                'ordering': ['sort_order', 'step_key'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant_key', models.CharField(max_length=32)),
                ('weight_percent', models.PositiveSmallIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='questionnaires.experiment')),
                ('questionnaire_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_variants', to='questionnaires.questionnaireversion')),
            ],
            options={
                'db_table': 'experiment_variants',
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(max_length=64)),
                ('field_type', models.CharField(choices=[('single_choice', 'Single choice'), ('multi_choice', 'Multi choice'), ('yes_no', 'Yes / No'), ('text', 'Text'), ('email', 'Email'), ('phone', 'Phone'), ('password', 'Password'), ('date', 'Date'), ('number', 'Number'), ('textarea', 'Textarea'), ('address_group', 'Address group'), ('plugin', 'Plugin')], max_length=32)),
                ('label', models.CharField(max_length=256)),
                ('help_text', models.TextField(blank=True, default='')),
                ('options', models.JSONField(blank=True, default=list)),
                ('validation_rules', models.JSONField(blank=True, default=list)),
                ('maps_to_section', models.CharField(blank=True, default='', max_length=64)),
                ('plugin_id', models.CharField(blank=True, default='', max_length=64)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='questionnaires.questionnairestep')),
            ],
            options={
                'db_table': 'questionnaire_fields',
                'ordering': ['sort_order', 'field_key'],
                'constraints': [models.UniqueConstraint(fields=('step', 'field_key'), name='unique_field_key_per_step')],
            },
        ),
        migrations.AddConstraint(
            model_name='questionnaireversion',
            constraint=models.UniqueConstraint(fields=('questionnaire', 'version_label'), name='unique_questionnaire_version_label'),
        ),
        migrations.AddConstraint(
            model_name='questionnairestep',
            constraint=models.UniqueConstraint(fields=('version', 'step_key'), name='unique_step_key_per_version'),
        ),
        migrations.AddConstraint(
            model_name='experimentvariant',
            constraint=models.UniqueConstraint(fields=('experiment', 'variant_key'), name='unique_variant_key_per_experiment'),
        ),
    ]
