# Generated by Django 5.2.15 on 2026-06-24 16:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_questionnaire_type(apps, schema_editor):
    Questionnaire = apps.get_model("questionnaires", "Questionnaire")
    Questionnaire.objects.filter(slug="intake").update(questionnaire_type="intake")
    Questionnaire.objects.filter(slug="qualify").update(questionnaire_type="qualify")


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('drug_type', models.CharField(choices=[('semaglutide', 'Semaglutide'), ('tirzepatide', 'Tirzepatide'), ('other', 'Other')], max_length=32)),
                ('delivery_type', models.CharField(choices=[('injection', 'Injection'), ('daily_pill', 'Daily pill')], max_length=16)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medications',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='questionnaire_type',
            field=models.CharField(choices=[('qualify', 'Qualify'), ('intake', 'Intake')], default='qualify', max_length=16),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='slug',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='questionnaires.medication'),
        ),
        migrations.RunPython(backfill_questionnaire_type, migrations.RunPython.noop),
    ]
