# Generated by Django 5.2.15 on 2026-06-16 02:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('more_info_needed', 'More information needed'), ('approved', 'Approved'), ('not_approved', 'Not approved'), ('prescription_sent', 'Prescription sent')], default='submitted', max_length=32)),
                ('internal_note', models.TextField(blank=True)),
                ('patient_note', models.TextField(blank=True)),
                ('decision', models.CharField(blank=True, choices=[('needs_more_info', 'Needs more information'), ('not_appropriate', 'Not appropriate'), ('labs_required', 'Labs required'), ('approved', 'Approved'), ('prescription_sent_outside', 'Prescription sent outside platform')], max_length=64)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_conducted', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'provider_reviews',
            },
        ),
    ]
