# Generated by Django 5.2.16 on 2026-07-09 01:19

import django.core.serializers.json
import django.db.models.deletion
import fernet_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intakes', '0011_alter_refillrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_event_id', models.CharField(max_length=128, unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stripe_webhook_events',
            },
        ),
        migrations.CreateModel(
            name='AuthorizationHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questionnaire_version_id', models.UUIDField(blank=True, null=True)),
                ('experiment_id', models.UUIDField(blank=True, null=True)),
                ('variant_key', models.CharField(blank=True, default='', max_length=32)),
                ('payment_mode', models.CharField(choices=[('auth_hold', 'Auth hold'), ('setup_only', 'Setup only')], max_length=16)),
                ('stripe_payment_intent_id', fernet_fields.fields.EncryptedCharField(blank=True, default='', max_length=128)),
                ('stripe_setup_intent_id', fernet_fields.fields.EncryptedCharField(blank=True, default='', max_length=128)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('pricing_config_snapshot', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('held', 'Held'), ('requires_action', 'Requires action'), ('captured', 'Captured'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='created', max_length=32)),
                ('status_reason', models.CharField(blank=True, default='', max_length=128)),
                ('captured_amount_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('held_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_holds', to='intakes.medicalintake')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_holds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'authorization_holds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_customer_id', fernet_fields.fields.EncryptedCharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stripe_customers',
            },
        ),
        migrations.CreateModel(
            name='StripePaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_payment_method_id', fernet_fields.fields.EncryptedCharField(max_length=64)),
                ('card_brand', models.CharField(blank=True, default='', max_length=16)),
                ('card_last4', models.CharField(blank=True, default='', max_length=4)),
                ('card_exp_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('card_exp_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=True)),
                ('stripe_setup_intent_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stripe_payment_methods',
                'ordering': ['-created_at'],
            },
        ),
    ]
