/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwitchRouteImport } from './routes/switch'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as QualifyRouteImport } from './routes/qualify'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CliniciansRouteImport } from './routes/clinicians'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalTelehealthConsentRouteImport } from './routes/legal.telehealth-consent'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'

const SwitchRoute = SwitchRouteImport.update({
  id: '/switch',
  path: '/switch',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const QualifyRoute = QualifyRouteImport.update({
  id: '/qualify',
  path: '/qualify',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CliniciansRoute = CliniciansRouteImport.update({
  id: '/clinicians',
  path: '/clinicians',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTelehealthConsentRoute = LegalTelehealthConsentRouteImport.update({
  id: '/legal/telehealth-consent',
  path: '/legal/telehealth-consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clinicians': typeof CliniciansRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/insurance': typeof InsuranceRoute
  '/learn': typeof LearnRoute
  '/pricing': typeof PricingRoute
  '/qualify': typeof QualifyRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/switch': typeof SwitchRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/telehealth-consent': typeof LegalTelehealthConsentRoute
  '/legal/terms': typeof LegalTermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clinicians': typeof CliniciansRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/insurance': typeof InsuranceRoute
  '/learn': typeof LearnRoute
  '/pricing': typeof PricingRoute
  '/qualify': typeof QualifyRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/switch': typeof SwitchRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/telehealth-consent': typeof LegalTelehealthConsentRoute
  '/legal/terms': typeof LegalTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clinicians': typeof CliniciansRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/insurance': typeof InsuranceRoute
  '/learn': typeof LearnRoute
  '/pricing': typeof PricingRoute
  '/qualify': typeof QualifyRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/switch': typeof SwitchRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/telehealth-consent': typeof LegalTelehealthConsentRoute
  '/legal/terms': typeof LegalTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clinicians'
    | '/faq'
    | '/how-it-works'
    | '/insurance'
    | '/learn'
    | '/pricing'
    | '/qualify'
    | '/safety'
    | '/sitemap.xml'
    | '/switch'
    | '/legal/privacy'
    | '/legal/telehealth-consent'
    | '/legal/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clinicians'
    | '/faq'
    | '/how-it-works'
    | '/insurance'
    | '/learn'
    | '/pricing'
    | '/qualify'
    | '/safety'
    | '/sitemap.xml'
    | '/switch'
    | '/legal/privacy'
    | '/legal/telehealth-consent'
    | '/legal/terms'
  id:
    | '__root__'
    | '/'
    | '/clinicians'
    | '/faq'
    | '/how-it-works'
    | '/insurance'
    | '/learn'
    | '/pricing'
    | '/qualify'
    | '/safety'
    | '/sitemap.xml'
    | '/switch'
    | '/legal/privacy'
    | '/legal/telehealth-consent'
    | '/legal/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CliniciansRoute: typeof CliniciansRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InsuranceRoute: typeof InsuranceRoute
  LearnRoute: typeof LearnRoute
  PricingRoute: typeof PricingRoute
  QualifyRoute: typeof QualifyRoute
  SafetyRoute: typeof SafetyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SwitchRoute: typeof SwitchRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTelehealthConsentRoute: typeof LegalTelehealthConsentRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/switch': {
      id: '/switch'
      path: '/switch'
      fullPath: '/switch'
      preLoaderRoute: typeof SwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualify': {
      id: '/qualify'
      path: '/qualify'
      fullPath: '/qualify'
      preLoaderRoute: typeof QualifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinicians': {
      id: '/clinicians'
      path: '/clinicians'
      fullPath: '/clinicians'
      preLoaderRoute: typeof CliniciansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/telehealth-consent': {
      id: '/legal/telehealth-consent'
      path: '/legal/telehealth-consent'
      fullPath: '/legal/telehealth-consent'
      preLoaderRoute: typeof LegalTelehealthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CliniciansRoute: CliniciansRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  InsuranceRoute: InsuranceRoute,
  LearnRoute: LearnRoute,
  PricingRoute: PricingRoute,
  QualifyRoute: QualifyRoute,
  SafetyRoute: SafetyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SwitchRoute: SwitchRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTelehealthConsentRoute: LegalTelehealthConsentRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
