/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeightLossRouteImport } from './routes/weight-loss'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SwitchRouteImport } from './routes/switch'
import { Route as SubmittedRouteImport } from './routes/submitted'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as QualifyRouteImport } from './routes/qualify'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as CliniciansRouteImport } from './routes/clinicians'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyEmailIndexRouteImport } from './routes/verify-email.index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as VerifyEmailPendingRouteImport } from './routes/verify-email.pending'
import { Route as StaffVendorsRouteImport } from './routes/staff.vendors'
import { Route as StaffQuestionnairesRouteImport } from './routes/staff.questionnaires'
import { Route as StaffPatientsRouteImport } from './routes/staff.patients'
import { Route as StaffMedicationsRouteImport } from './routes/staff.medications'
import { Route as StaffLandingPagesRouteImport } from './routes/staff.landing-pages'
import { Route as StaffExperimentsRouteImport } from './routes/staff.experiments'
import { Route as StaffDevRouteImport } from './routes/staff.dev'
import { Route as StaffAnalyticsRouteImport } from './routes/staff.analytics'
import { Route as LpSlugRouteImport } from './routes/lp.$slug'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalTelehealthConsentRouteImport } from './routes/legal.telehealth-consent'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalIntakeAcknowledgmentsRouteImport } from './routes/legal.intake-acknowledgments'
import { Route as DashboardRefillsRouteImport } from './routes/dashboard.refills'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardIntakeRouteImport } from './routes/dashboard.intake'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard.documents'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'
import { Route as StaffQuestionnairesIndexRouteImport } from './routes/staff.questionnaires.index'
import { Route as StaffQuestionnairesSlugRouteImport } from './routes/staff.questionnaires.$slug'
import { Route as StaffQuestionnairesSlugIndexRouteImport } from './routes/staff.questionnaires.$slug.index'
import { Route as StaffQuestionnairesSlugVersionsVersionIdRouteImport } from './routes/staff.questionnaires.$slug.versions.$versionId'

const WeightLossRoute = WeightLossRouteImport.update({
  id: '/weight-loss',
  path: '/weight-loss',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SwitchRoute = SwitchRouteImport.update({
  id: '/switch',
  path: '/switch',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmittedRoute = SubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const QualifyRoute = QualifyRouteImport.update({
  id: '/qualify',
  path: '/qualify',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const CliniciansRoute = CliniciansRouteImport.update({
  id: '/clinicians',
  path: '/clinicians',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailIndexRoute = VerifyEmailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VerifyEmailRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const VerifyEmailPendingRoute = VerifyEmailPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => VerifyEmailRoute,
} as any)
const StaffVendorsRoute = StaffVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => StaffRoute,
} as any)
const StaffQuestionnairesRoute = StaffQuestionnairesRouteImport.update({
  id: '/questionnaires',
  path: '/questionnaires',
  getParentRoute: () => StaffRoute,
} as any)
const StaffPatientsRoute = StaffPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => StaffRoute,
} as any)
const StaffMedicationsRoute = StaffMedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => StaffRoute,
} as any)
const StaffLandingPagesRoute = StaffLandingPagesRouteImport.update({
  id: '/landing-pages',
  path: '/landing-pages',
  getParentRoute: () => StaffRoute,
} as any)
const StaffExperimentsRoute = StaffExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => StaffRoute,
} as any)
const StaffDevRoute = StaffDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAnalyticsRoute = StaffAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => StaffRoute,
} as any)
const LpSlugRoute = LpSlugRouteImport.update({
  id: '/lp/$slug',
  path: '/lp/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTelehealthConsentRoute = LegalTelehealthConsentRouteImport.update({
  id: '/legal/telehealth-consent',
  path: '/legal/telehealth-consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIntakeAcknowledgmentsRoute =
  LegalIntakeAcknowledgmentsRouteImport.update({
    id: '/legal/intake-acknowledgments',
    path: '/legal/intake-acknowledgments',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardRefillsRoute = DashboardRefillsRouteImport.update({
  id: '/refills',
  path: '/refills',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntakeRoute = DashboardIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const StaffQuestionnairesIndexRoute =
  StaffQuestionnairesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StaffQuestionnairesRoute,
  } as any)
const StaffQuestionnairesSlugRoute = StaffQuestionnairesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StaffQuestionnairesRoute,
} as any)
const StaffQuestionnairesSlugIndexRoute =
  StaffQuestionnairesSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StaffQuestionnairesSlugRoute,
  } as any)
const StaffQuestionnairesSlugVersionsVersionIdRoute =
  StaffQuestionnairesSlugVersionsVersionIdRouteImport.update({
    id: '/versions/$versionId',
    path: '/versions/$versionId',
    getParentRoute: () => StaffQuestionnairesSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clinicians': typeof CliniciansRoute
  '/consent': typeof ConsentRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/eligibility': typeof EligibilityRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/insurance': typeof InsuranceRoute
  '/intake': typeof IntakeRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/qualify': typeof QualifyRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRouteWithChildren
  '/submitted': typeof SubmittedRoute
  '/switch': typeof SwitchRoute
  '/verify-email': typeof VerifyEmailRouteWithChildren
  '/weight-loss': typeof WeightLossRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/intake': typeof DashboardIntakeRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/refills': typeof DashboardRefillsRoute
  '/legal/intake-acknowledgments': typeof LegalIntakeAcknowledgmentsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/telehealth-consent': typeof LegalTelehealthConsentRoute
  '/legal/terms': typeof LegalTermsRoute
  '/lp/$slug': typeof LpSlugRoute
  '/staff/analytics': typeof StaffAnalyticsRoute
  '/staff/dev': typeof StaffDevRoute
  '/staff/experiments': typeof StaffExperimentsRoute
  '/staff/landing-pages': typeof StaffLandingPagesRoute
  '/staff/medications': typeof StaffMedicationsRoute
  '/staff/patients': typeof StaffPatientsRoute
  '/staff/questionnaires': typeof StaffQuestionnairesRouteWithChildren
  '/staff/vendors': typeof StaffVendorsRoute
  '/verify-email/pending': typeof VerifyEmailPendingRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/verify-email/': typeof VerifyEmailIndexRoute
  '/staff/questionnaires/$slug': typeof StaffQuestionnairesSlugRouteWithChildren
  '/staff/questionnaires/': typeof StaffQuestionnairesIndexRoute
  '/staff/questionnaires/$slug/': typeof StaffQuestionnairesSlugIndexRoute
  '/staff/questionnaires/$slug/versions/$versionId': typeof StaffQuestionnairesSlugVersionsVersionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clinicians': typeof CliniciansRoute
  '/consent': typeof ConsentRoute
  '/contact': typeof ContactRoute
  '/eligibility': typeof EligibilityRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/insurance': typeof InsuranceRoute
  '/intake': typeof IntakeRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/qualify': typeof QualifyRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submitted': typeof SubmittedRoute
  '/switch': typeof SwitchRoute
  '/weight-loss': typeof WeightLossRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/intake': typeof DashboardIntakeRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/refills': typeof DashboardRefillsRoute
  '/legal/intake-acknowledgments': typeof LegalIntakeAcknowledgmentsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/telehealth-consent': typeof LegalTelehealthConsentRoute
  '/legal/terms': typeof LegalTermsRoute
  '/lp/$slug': typeof LpSlugRoute
  '/staff/analytics': typeof StaffAnalyticsRoute
  '/staff/dev': typeof StaffDevRoute
  '/staff/experiments': typeof StaffExperimentsRoute
  '/staff/landing-pages': typeof StaffLandingPagesRoute
  '/staff/medications': typeof StaffMedicationsRoute
  '/staff/patients': typeof StaffPatientsRoute
  '/staff/vendors': typeof StaffVendorsRoute
  '/verify-email/pending': typeof VerifyEmailPendingRoute
  '/dashboard': typeof DashboardIndexRoute
  '/staff': typeof StaffIndexRoute
  '/verify-email': typeof VerifyEmailIndexRoute
  '/staff/questionnaires': typeof StaffQuestionnairesIndexRoute
  '/staff/questionnaires/$slug': typeof StaffQuestionnairesSlugIndexRoute
  '/staff/questionnaires/$slug/versions/$versionId': typeof StaffQuestionnairesSlugVersionsVersionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clinicians': typeof CliniciansRoute
  '/consent': typeof ConsentRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/eligibility': typeof EligibilityRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/insurance': typeof InsuranceRoute
  '/intake': typeof IntakeRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/qualify': typeof QualifyRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRouteWithChildren
  '/submitted': typeof SubmittedRoute
  '/switch': typeof SwitchRoute
  '/verify-email': typeof VerifyEmailRouteWithChildren
  '/weight-loss': typeof WeightLossRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/intake': typeof DashboardIntakeRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/refills': typeof DashboardRefillsRoute
  '/legal/intake-acknowledgments': typeof LegalIntakeAcknowledgmentsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/telehealth-consent': typeof LegalTelehealthConsentRoute
  '/legal/terms': typeof LegalTermsRoute
  '/lp/$slug': typeof LpSlugRoute
  '/staff/analytics': typeof StaffAnalyticsRoute
  '/staff/dev': typeof StaffDevRoute
  '/staff/experiments': typeof StaffExperimentsRoute
  '/staff/landing-pages': typeof StaffLandingPagesRoute
  '/staff/medications': typeof StaffMedicationsRoute
  '/staff/patients': typeof StaffPatientsRoute
  '/staff/questionnaires': typeof StaffQuestionnairesRouteWithChildren
  '/staff/vendors': typeof StaffVendorsRoute
  '/verify-email/pending': typeof VerifyEmailPendingRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/verify-email/': typeof VerifyEmailIndexRoute
  '/staff/questionnaires/$slug': typeof StaffQuestionnairesSlugRouteWithChildren
  '/staff/questionnaires/': typeof StaffQuestionnairesIndexRoute
  '/staff/questionnaires/$slug/': typeof StaffQuestionnairesSlugIndexRoute
  '/staff/questionnaires/$slug/versions/$versionId': typeof StaffQuestionnairesSlugVersionsVersionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clinicians'
    | '/consent'
    | '/contact'
    | '/dashboard'
    | '/eligibility'
    | '/faq'
    | '/how-it-works'
    | '/insurance'
    | '/intake'
    | '/learn'
    | '/login'
    | '/pricing'
    | '/qualify'
    | '/safety'
    | '/sitemap.xml'
    | '/staff'
    | '/submitted'
    | '/switch'
    | '/verify-email'
    | '/weight-loss'
    | '/dashboard/account'
    | '/dashboard/documents'
    | '/dashboard/intake'
    | '/dashboard/orders'
    | '/dashboard/refills'
    | '/legal/intake-acknowledgments'
    | '/legal/privacy'
    | '/legal/telehealth-consent'
    | '/legal/terms'
    | '/lp/$slug'
    | '/staff/analytics'
    | '/staff/dev'
    | '/staff/experiments'
    | '/staff/landing-pages'
    | '/staff/medications'
    | '/staff/patients'
    | '/staff/questionnaires'
    | '/staff/vendors'
    | '/verify-email/pending'
    | '/dashboard/'
    | '/staff/'
    | '/verify-email/'
    | '/staff/questionnaires/$slug'
    | '/staff/questionnaires/'
    | '/staff/questionnaires/$slug/'
    | '/staff/questionnaires/$slug/versions/$versionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clinicians'
    | '/consent'
    | '/contact'
    | '/eligibility'
    | '/faq'
    | '/how-it-works'
    | '/insurance'
    | '/intake'
    | '/learn'
    | '/login'
    | '/pricing'
    | '/qualify'
    | '/safety'
    | '/sitemap.xml'
    | '/submitted'
    | '/switch'
    | '/weight-loss'
    | '/dashboard/account'
    | '/dashboard/documents'
    | '/dashboard/intake'
    | '/dashboard/orders'
    | '/dashboard/refills'
    | '/legal/intake-acknowledgments'
    | '/legal/privacy'
    | '/legal/telehealth-consent'
    | '/legal/terms'
    | '/lp/$slug'
    | '/staff/analytics'
    | '/staff/dev'
    | '/staff/experiments'
    | '/staff/landing-pages'
    | '/staff/medications'
    | '/staff/patients'
    | '/staff/vendors'
    | '/verify-email/pending'
    | '/dashboard'
    | '/staff'
    | '/verify-email'
    | '/staff/questionnaires'
    | '/staff/questionnaires/$slug'
    | '/staff/questionnaires/$slug/versions/$versionId'
  id:
    | '__root__'
    | '/'
    | '/clinicians'
    | '/consent'
    | '/contact'
    | '/dashboard'
    | '/eligibility'
    | '/faq'
    | '/how-it-works'
    | '/insurance'
    | '/intake'
    | '/learn'
    | '/login'
    | '/pricing'
    | '/qualify'
    | '/safety'
    | '/sitemap.xml'
    | '/staff'
    | '/submitted'
    | '/switch'
    | '/verify-email'
    | '/weight-loss'
    | '/dashboard/account'
    | '/dashboard/documents'
    | '/dashboard/intake'
    | '/dashboard/orders'
    | '/dashboard/refills'
    | '/legal/intake-acknowledgments'
    | '/legal/privacy'
    | '/legal/telehealth-consent'
    | '/legal/terms'
    | '/lp/$slug'
    | '/staff/analytics'
    | '/staff/dev'
    | '/staff/experiments'
    | '/staff/landing-pages'
    | '/staff/medications'
    | '/staff/patients'
    | '/staff/questionnaires'
    | '/staff/vendors'
    | '/verify-email/pending'
    | '/dashboard/'
    | '/staff/'
    | '/verify-email/'
    | '/staff/questionnaires/$slug'
    | '/staff/questionnaires/'
    | '/staff/questionnaires/$slug/'
    | '/staff/questionnaires/$slug/versions/$versionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CliniciansRoute: typeof CliniciansRoute
  ConsentRoute: typeof ConsentRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EligibilityRoute: typeof EligibilityRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InsuranceRoute: typeof InsuranceRoute
  IntakeRoute: typeof IntakeRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  QualifyRoute: typeof QualifyRoute
  SafetyRoute: typeof SafetyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StaffRoute: typeof StaffRouteWithChildren
  SubmittedRoute: typeof SubmittedRoute
  SwitchRoute: typeof SwitchRoute
  VerifyEmailRoute: typeof VerifyEmailRouteWithChildren
  WeightLossRoute: typeof WeightLossRoute
  LegalIntakeAcknowledgmentsRoute: typeof LegalIntakeAcknowledgmentsRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTelehealthConsentRoute: typeof LegalTelehealthConsentRoute
  LegalTermsRoute: typeof LegalTermsRoute
  LpSlugRoute: typeof LpSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weight-loss': {
      id: '/weight-loss'
      path: '/weight-loss'
      fullPath: '/weight-loss'
      preLoaderRoute: typeof WeightLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/switch': {
      id: '/switch'
      path: '/switch'
      fullPath: '/switch'
      preLoaderRoute: typeof SwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submitted': {
      id: '/submitted'
      path: '/submitted'
      fullPath: '/submitted'
      preLoaderRoute: typeof SubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualify': {
      id: '/qualify'
      path: '/qualify'
      fullPath: '/qualify'
      preLoaderRoute: typeof QualifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinicians': {
      id: '/clinicians'
      path: '/clinicians'
      fullPath: '/clinicians'
      preLoaderRoute: typeof CliniciansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email/': {
      id: '/verify-email/'
      path: '/'
      fullPath: '/verify-email/'
      preLoaderRoute: typeof VerifyEmailIndexRouteImport
      parentRoute: typeof VerifyEmailRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/verify-email/pending': {
      id: '/verify-email/pending'
      path: '/pending'
      fullPath: '/verify-email/pending'
      preLoaderRoute: typeof VerifyEmailPendingRouteImport
      parentRoute: typeof VerifyEmailRoute
    }
    '/staff/vendors': {
      id: '/staff/vendors'
      path: '/vendors'
      fullPath: '/staff/vendors'
      preLoaderRoute: typeof StaffVendorsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/questionnaires': {
      id: '/staff/questionnaires'
      path: '/questionnaires'
      fullPath: '/staff/questionnaires'
      preLoaderRoute: typeof StaffQuestionnairesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/patients': {
      id: '/staff/patients'
      path: '/patients'
      fullPath: '/staff/patients'
      preLoaderRoute: typeof StaffPatientsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/medications': {
      id: '/staff/medications'
      path: '/medications'
      fullPath: '/staff/medications'
      preLoaderRoute: typeof StaffMedicationsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/landing-pages': {
      id: '/staff/landing-pages'
      path: '/landing-pages'
      fullPath: '/staff/landing-pages'
      preLoaderRoute: typeof StaffLandingPagesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/experiments': {
      id: '/staff/experiments'
      path: '/experiments'
      fullPath: '/staff/experiments'
      preLoaderRoute: typeof StaffExperimentsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/dev': {
      id: '/staff/dev'
      path: '/dev'
      fullPath: '/staff/dev'
      preLoaderRoute: typeof StaffDevRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/analytics': {
      id: '/staff/analytics'
      path: '/analytics'
      fullPath: '/staff/analytics'
      preLoaderRoute: typeof StaffAnalyticsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/lp/$slug': {
      id: '/lp/$slug'
      path: '/lp/$slug'
      fullPath: '/lp/$slug'
      preLoaderRoute: typeof LpSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/telehealth-consent': {
      id: '/legal/telehealth-consent'
      path: '/legal/telehealth-consent'
      fullPath: '/legal/telehealth-consent'
      preLoaderRoute: typeof LegalTelehealthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/intake-acknowledgments': {
      id: '/legal/intake-acknowledgments'
      path: '/legal/intake-acknowledgments'
      fullPath: '/legal/intake-acknowledgments'
      preLoaderRoute: typeof LegalIntakeAcknowledgmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/refills': {
      id: '/dashboard/refills'
      path: '/refills'
      fullPath: '/dashboard/refills'
      preLoaderRoute: typeof DashboardRefillsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/intake': {
      id: '/dashboard/intake'
      path: '/intake'
      fullPath: '/dashboard/intake'
      preLoaderRoute: typeof DashboardIntakeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/staff/questionnaires/': {
      id: '/staff/questionnaires/'
      path: '/'
      fullPath: '/staff/questionnaires/'
      preLoaderRoute: typeof StaffQuestionnairesIndexRouteImport
      parentRoute: typeof StaffQuestionnairesRoute
    }
    '/staff/questionnaires/$slug': {
      id: '/staff/questionnaires/$slug'
      path: '/$slug'
      fullPath: '/staff/questionnaires/$slug'
      preLoaderRoute: typeof StaffQuestionnairesSlugRouteImport
      parentRoute: typeof StaffQuestionnairesRoute
    }
    '/staff/questionnaires/$slug/': {
      id: '/staff/questionnaires/$slug/'
      path: '/'
      fullPath: '/staff/questionnaires/$slug/'
      preLoaderRoute: typeof StaffQuestionnairesSlugIndexRouteImport
      parentRoute: typeof StaffQuestionnairesSlugRoute
    }
    '/staff/questionnaires/$slug/versions/$versionId': {
      id: '/staff/questionnaires/$slug/versions/$versionId'
      path: '/versions/$versionId'
      fullPath: '/staff/questionnaires/$slug/versions/$versionId'
      preLoaderRoute: typeof StaffQuestionnairesSlugVersionsVersionIdRouteImport
      parentRoute: typeof StaffQuestionnairesSlugRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardIntakeRoute: typeof DashboardIntakeRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardRefillsRoute: typeof DashboardRefillsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardIntakeRoute: DashboardIntakeRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardRefillsRoute: DashboardRefillsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface StaffQuestionnairesSlugRouteChildren {
  StaffQuestionnairesSlugIndexRoute: typeof StaffQuestionnairesSlugIndexRoute
  StaffQuestionnairesSlugVersionsVersionIdRoute: typeof StaffQuestionnairesSlugVersionsVersionIdRoute
}

const StaffQuestionnairesSlugRouteChildren: StaffQuestionnairesSlugRouteChildren =
  {
    StaffQuestionnairesSlugIndexRoute: StaffQuestionnairesSlugIndexRoute,
    StaffQuestionnairesSlugVersionsVersionIdRoute:
      StaffQuestionnairesSlugVersionsVersionIdRoute,
  }

const StaffQuestionnairesSlugRouteWithChildren =
  StaffQuestionnairesSlugRoute._addFileChildren(
    StaffQuestionnairesSlugRouteChildren,
  )

interface StaffQuestionnairesRouteChildren {
  StaffQuestionnairesSlugRoute: typeof StaffQuestionnairesSlugRouteWithChildren
  StaffQuestionnairesIndexRoute: typeof StaffQuestionnairesIndexRoute
}

const StaffQuestionnairesRouteChildren: StaffQuestionnairesRouteChildren = {
  StaffQuestionnairesSlugRoute: StaffQuestionnairesSlugRouteWithChildren,
  StaffQuestionnairesIndexRoute: StaffQuestionnairesIndexRoute,
}

const StaffQuestionnairesRouteWithChildren =
  StaffQuestionnairesRoute._addFileChildren(StaffQuestionnairesRouteChildren)

interface StaffRouteChildren {
  StaffAnalyticsRoute: typeof StaffAnalyticsRoute
  StaffDevRoute: typeof StaffDevRoute
  StaffExperimentsRoute: typeof StaffExperimentsRoute
  StaffLandingPagesRoute: typeof StaffLandingPagesRoute
  StaffMedicationsRoute: typeof StaffMedicationsRoute
  StaffPatientsRoute: typeof StaffPatientsRoute
  StaffQuestionnairesRoute: typeof StaffQuestionnairesRouteWithChildren
  StaffVendorsRoute: typeof StaffVendorsRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAnalyticsRoute: StaffAnalyticsRoute,
  StaffDevRoute: StaffDevRoute,
  StaffExperimentsRoute: StaffExperimentsRoute,
  StaffLandingPagesRoute: StaffLandingPagesRoute,
  StaffMedicationsRoute: StaffMedicationsRoute,
  StaffPatientsRoute: StaffPatientsRoute,
  StaffQuestionnairesRoute: StaffQuestionnairesRouteWithChildren,
  StaffVendorsRoute: StaffVendorsRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface VerifyEmailRouteChildren {
  VerifyEmailPendingRoute: typeof VerifyEmailPendingRoute
  VerifyEmailIndexRoute: typeof VerifyEmailIndexRoute
}

const VerifyEmailRouteChildren: VerifyEmailRouteChildren = {
  VerifyEmailPendingRoute: VerifyEmailPendingRoute,
  VerifyEmailIndexRoute: VerifyEmailIndexRoute,
}

const VerifyEmailRouteWithChildren = VerifyEmailRoute._addFileChildren(
  VerifyEmailRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CliniciansRoute: CliniciansRoute,
  ConsentRoute: ConsentRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EligibilityRoute: EligibilityRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  InsuranceRoute: InsuranceRoute,
  IntakeRoute: IntakeRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  QualifyRoute: QualifyRoute,
  SafetyRoute: SafetyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StaffRoute: StaffRouteWithChildren,
  SubmittedRoute: SubmittedRoute,
  SwitchRoute: SwitchRoute,
  VerifyEmailRoute: VerifyEmailRouteWithChildren,
  WeightLossRoute: WeightLossRoute,
  LegalIntakeAcknowledgmentsRoute: LegalIntakeAcknowledgmentsRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTelehealthConsentRoute: LegalTelehealthConsentRoute,
  LegalTermsRoute: LegalTermsRoute,
  LpSlugRoute: LpSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
