/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeightLossRouteImport } from './routes/weight-loss'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TirzepatideRouteImport } from './routes/tirzepatide'
import { Route as TadalafilRouteImport } from './routes/tadalafil'
import { Route as SubmittedRouteImport } from './routes/submitted'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SildenafilRouteImport } from './routes/sildenafil'
import { Route as SexualHealthRouteImport } from './routes/sexual-health'
import { Route as SermorelinRouteImport } from './routes/sermorelin'
import { Route as SemaglutideRouteImport } from './routes/semaglutide'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as QualifyRouteImport } from './routes/qualify'
import { Route as OralMinoxidilWomenRouteImport } from './routes/oral-minoxidil-women'
import { Route as OralMinoxidilMenRouteImport } from './routes/oral-minoxidil-men'
import { Route as OralFinasterideRouteImport } from './routes/oral-finasteride'
import { Route as NadPlusRouteImport } from './routes/nad-plus'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HairLossSprayWomenRouteImport } from './routes/hair-loss-spray-women'
import { Route as HairLossSprayMenRouteImport } from './routes/hair-loss-spray-men'
import { Route as HairLossRouteImport } from './routes/hair-loss'
import { Route as Glp1HoustonRouteImport } from './routes/glp-1-houston'
import { Route as Glp1RouteImport } from './routes/glp-1'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as EdMintsRouteImport } from './routes/ed-mints'
import { Route as EdRouteImport } from './routes/ed'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyEmailIndexRouteImport } from './routes/verify-email.index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as VerifyEmailPendingRouteImport } from './routes/verify-email.pending'
import { Route as StaffVendorsRouteImport } from './routes/staff.vendors'
import { Route as StaffQuestionnairesRouteImport } from './routes/staff.questionnaires'
import { Route as StaffPatientsRouteImport } from './routes/staff.patients'
import { Route as StaffMedicationsRouteImport } from './routes/staff.medications'
import { Route as StaffLandingPagesRouteImport } from './routes/staff.landing-pages'
import { Route as StaffExperimentsRouteImport } from './routes/staff.experiments'
import { Route as StaffDevRouteImport } from './routes/staff.dev'
import { Route as StaffAnalyticsRouteImport } from './routes/staff.analytics'
import { Route as RecipesSlugRouteImport } from './routes/recipes/$slug'
import { Route as LpSlugRouteImport } from './routes/lp.$slug'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalTelehealthConsentRouteImport } from './routes/legal.telehealth-consent'
import { Route as LegalShippingRouteImport } from './routes/legal.shipping'
import { Route as LegalRefundRouteImport } from './routes/legal.refund'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalPhysicianCodeOfConductRouteImport } from './routes/legal.physician-code-of-conduct'
import { Route as LegalIntakeAcknowledgmentsRouteImport } from './routes/legal.intake-acknowledgments'
import { Route as LegalHipaaRouteImport } from './routes/legal.hipaa'
import { Route as LearnSemaglutideVsTirzepatideRouteImport } from './routes/learn.semaglutide-vs-tirzepatide'
import { Route as LearnRestIntervalsRouteImport } from './routes/learn.rest-intervals'
import { Route as LearnResistanceTrainingRouteImport } from './routes/learn.resistance-training'
import { Route as LearnInitialResearchRouteImport } from './routes/learn.initial-research'
import { Route as LearnVerticalRouteImport } from './routes/learn/$vertical'
import { Route as DashboardRefillsRouteImport } from './routes/dashboard.refills'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardIntakeRouteImport } from './routes/dashboard.intake'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard.documents'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'
import { Route as StaffQuestionnairesIndexRouteImport } from './routes/staff.questionnaires.index'
import { Route as LearnVerticalIndexRouteImport } from './routes/learn/$vertical.index'
import { Route as StaffQuestionnairesSlugRouteImport } from './routes/staff.questionnaires.$slug'
import { Route as LearnVerticalSlugRouteImport } from './routes/learn/$vertical.$slug'
import { Route as StaffQuestionnairesSlugIndexRouteImport } from './routes/staff.questionnaires.$slug.index'
import { Route as StaffQuestionnairesSlugVersionsVersionIdRouteImport } from './routes/staff.questionnaires.$slug.versions.$versionId'

const WeightLossRoute = WeightLossRouteImport.update({
  id: '/weight-loss',
  path: '/weight-loss',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TirzepatideRoute = TirzepatideRouteImport.update({
  id: '/tirzepatide',
  path: '/tirzepatide',
  getParentRoute: () => rootRouteImport,
} as any)
const TadalafilRoute = TadalafilRouteImport.update({
  id: '/tadalafil',
  path: '/tadalafil',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmittedRoute = SubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SildenafilRoute = SildenafilRouteImport.update({
  id: '/sildenafil',
  path: '/sildenafil',
  getParentRoute: () => rootRouteImport,
} as any)
const SexualHealthRoute = SexualHealthRouteImport.update({
  id: '/sexual-health',
  path: '/sexual-health',
  getParentRoute: () => rootRouteImport,
} as any)
const SermorelinRoute = SermorelinRouteImport.update({
  id: '/sermorelin',
  path: '/sermorelin',
  getParentRoute: () => rootRouteImport,
} as any)
const SemaglutideRoute = SemaglutideRouteImport.update({
  id: '/semaglutide',
  path: '/semaglutide',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const QualifyRoute = QualifyRouteImport.update({
  id: '/qualify',
  path: '/qualify',
  getParentRoute: () => rootRouteImport,
} as any)
const OralMinoxidilWomenRoute = OralMinoxidilWomenRouteImport.update({
  id: '/oral-minoxidil-women',
  path: '/oral-minoxidil-women',
  getParentRoute: () => rootRouteImport,
} as any)
const OralMinoxidilMenRoute = OralMinoxidilMenRouteImport.update({
  id: '/oral-minoxidil-men',
  path: '/oral-minoxidil-men',
  getParentRoute: () => rootRouteImport,
} as any)
const OralFinasterideRoute = OralFinasterideRouteImport.update({
  id: '/oral-finasteride',
  path: '/oral-finasteride',
  getParentRoute: () => rootRouteImport,
} as any)
const NadPlusRoute = NadPlusRouteImport.update({
  id: '/nad-plus',
  path: '/nad-plus',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HairLossSprayWomenRoute = HairLossSprayWomenRouteImport.update({
  id: '/hair-loss-spray-women',
  path: '/hair-loss-spray-women',
  getParentRoute: () => rootRouteImport,
} as any)
const HairLossSprayMenRoute = HairLossSprayMenRouteImport.update({
  id: '/hair-loss-spray-men',
  path: '/hair-loss-spray-men',
  getParentRoute: () => rootRouteImport,
} as any)
const HairLossRoute = HairLossRouteImport.update({
  id: '/hair-loss',
  path: '/hair-loss',
  getParentRoute: () => rootRouteImport,
} as any)
const Glp1HoustonRoute = Glp1HoustonRouteImport.update({
  id: '/glp-1-houston',
  path: '/glp-1-houston',
  getParentRoute: () => rootRouteImport,
} as any)
const Glp1Route = Glp1RouteImport.update({
  id: '/glp-1',
  path: '/glp-1',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const EdMintsRoute = EdMintsRouteImport.update({
  id: '/ed-mints',
  path: '/ed-mints',
  getParentRoute: () => rootRouteImport,
} as any)
const EdRoute = EdRouteImport.update({
  id: '/ed',
  path: '/ed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailIndexRoute = VerifyEmailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VerifyEmailRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const VerifyEmailPendingRoute = VerifyEmailPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => VerifyEmailRoute,
} as any)
const StaffVendorsRoute = StaffVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => StaffRoute,
} as any)
const StaffQuestionnairesRoute = StaffQuestionnairesRouteImport.update({
  id: '/questionnaires',
  path: '/questionnaires',
  getParentRoute: () => StaffRoute,
} as any)
const StaffPatientsRoute = StaffPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => StaffRoute,
} as any)
const StaffMedicationsRoute = StaffMedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => StaffRoute,
} as any)
const StaffLandingPagesRoute = StaffLandingPagesRouteImport.update({
  id: '/landing-pages',
  path: '/landing-pages',
  getParentRoute: () => StaffRoute,
} as any)
const StaffExperimentsRoute = StaffExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => StaffRoute,
} as any)
const StaffDevRoute = StaffDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAnalyticsRoute = StaffAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => StaffRoute,
} as any)
const RecipesSlugRoute = RecipesSlugRouteImport.update({
  id: '/recipes/$slug',
  path: '/recipes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LpSlugRoute = LpSlugRouteImport.update({
  id: '/lp/$slug',
  path: '/lp/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTelehealthConsentRoute = LegalTelehealthConsentRouteImport.update({
  id: '/legal/telehealth-consent',
  path: '/legal/telehealth-consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalShippingRoute = LegalShippingRouteImport.update({
  id: '/legal/shipping',
  path: '/legal/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/legal/refund',
  path: '/legal/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPhysicianCodeOfConductRoute =
  LegalPhysicianCodeOfConductRouteImport.update({
    id: '/legal/physician-code-of-conduct',
    path: '/legal/physician-code-of-conduct',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalIntakeAcknowledgmentsRoute =
  LegalIntakeAcknowledgmentsRouteImport.update({
    id: '/legal/intake-acknowledgments',
    path: '/legal/intake-acknowledgments',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalHipaaRoute = LegalHipaaRouteImport.update({
  id: '/legal/hipaa',
  path: '/legal/hipaa',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSemaglutideVsTirzepatideRoute =
  LearnSemaglutideVsTirzepatideRouteImport.update({
    id: '/semaglutide-vs-tirzepatide',
    path: '/semaglutide-vs-tirzepatide',
    getParentRoute: () => LearnRoute,
  } as any)
const LearnRestIntervalsRoute = LearnRestIntervalsRouteImport.update({
  id: '/rest-intervals',
  path: '/rest-intervals',
  getParentRoute: () => LearnRoute,
} as any)
const LearnResistanceTrainingRoute = LearnResistanceTrainingRouteImport.update({
  id: '/resistance-training',
  path: '/resistance-training',
  getParentRoute: () => LearnRoute,
} as any)
const LearnInitialResearchRoute = LearnInitialResearchRouteImport.update({
  id: '/initial-research',
  path: '/initial-research',
  getParentRoute: () => LearnRoute,
} as any)
const LearnVerticalRoute = LearnVerticalRouteImport.update({
  id: '/$vertical',
  path: '/$vertical',
  getParentRoute: () => LearnRoute,
} as any)
const DashboardRefillsRoute = DashboardRefillsRouteImport.update({
  id: '/refills',
  path: '/refills',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntakeRoute = DashboardIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const StaffQuestionnairesIndexRoute =
  StaffQuestionnairesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StaffQuestionnairesRoute,
  } as any)
const LearnVerticalIndexRoute = LearnVerticalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnVerticalRoute,
} as any)
const StaffQuestionnairesSlugRoute = StaffQuestionnairesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StaffQuestionnairesRoute,
} as any)
const LearnVerticalSlugRoute = LearnVerticalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LearnVerticalRoute,
} as any)
const StaffQuestionnairesSlugIndexRoute =
  StaffQuestionnairesSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StaffQuestionnairesSlugRoute,
  } as any)
const StaffQuestionnairesSlugVersionsVersionIdRoute =
  StaffQuestionnairesSlugVersionsVersionIdRouteImport.update({
    id: '/versions/$versionId',
    path: '/versions/$versionId',
    getParentRoute: () => StaffQuestionnairesSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consent': typeof ConsentRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/ed': typeof EdRoute
  '/ed-mints': typeof EdMintsRoute
  '/eligibility': typeof EligibilityRoute
  '/faq': typeof FaqRoute
  '/glp-1': typeof Glp1Route
  '/glp-1-houston': typeof Glp1HoustonRoute
  '/hair-loss': typeof HairLossRoute
  '/hair-loss-spray-men': typeof HairLossSprayMenRoute
  '/hair-loss-spray-women': typeof HairLossSprayWomenRoute
  '/how-it-works': typeof HowItWorksRoute
  '/intake': typeof IntakeRoute
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/nad-plus': typeof NadPlusRoute
  '/oral-finasteride': typeof OralFinasterideRoute
  '/oral-minoxidil-men': typeof OralMinoxidilMenRoute
  '/oral-minoxidil-women': typeof OralMinoxidilWomenRoute
  '/qualify': typeof QualifyRoute
  '/safety': typeof SafetyRoute
  '/semaglutide': typeof SemaglutideRoute
  '/sermorelin': typeof SermorelinRoute
  '/sexual-health': typeof SexualHealthRoute
  '/sildenafil': typeof SildenafilRoute
  '/staff': typeof StaffRouteWithChildren
  '/submitted': typeof SubmittedRoute
  '/tadalafil': typeof TadalafilRoute
  '/tirzepatide': typeof TirzepatideRoute
  '/verify-email': typeof VerifyEmailRouteWithChildren
  '/waitlist': typeof WaitlistRoute
  '/weight-loss': typeof WeightLossRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/intake': typeof DashboardIntakeRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/refills': typeof DashboardRefillsRoute
  '/learn/$vertical': typeof LearnVerticalRouteWithChildren
  '/learn/initial-research': typeof LearnInitialResearchRoute
  '/learn/resistance-training': typeof LearnResistanceTrainingRoute
  '/learn/rest-intervals': typeof LearnRestIntervalsRoute
  '/learn/semaglutide-vs-tirzepatide': typeof LearnSemaglutideVsTirzepatideRoute
  '/legal/hipaa': typeof LegalHipaaRoute
  '/legal/intake-acknowledgments': typeof LegalIntakeAcknowledgmentsRoute
  '/legal/physician-code-of-conduct': typeof LegalPhysicianCodeOfConductRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/shipping': typeof LegalShippingRoute
  '/legal/telehealth-consent': typeof LegalTelehealthConsentRoute
  '/legal/terms': typeof LegalTermsRoute
  '/lp/$slug': typeof LpSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/staff/analytics': typeof StaffAnalyticsRoute
  '/staff/dev': typeof StaffDevRoute
  '/staff/experiments': typeof StaffExperimentsRoute
  '/staff/landing-pages': typeof StaffLandingPagesRoute
  '/staff/medications': typeof StaffMedicationsRoute
  '/staff/patients': typeof StaffPatientsRoute
  '/staff/questionnaires': typeof StaffQuestionnairesRouteWithChildren
  '/staff/vendors': typeof StaffVendorsRoute
  '/verify-email/pending': typeof VerifyEmailPendingRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/verify-email/': typeof VerifyEmailIndexRoute
  '/learn/$vertical/$slug': typeof LearnVerticalSlugRoute
  '/staff/questionnaires/$slug': typeof StaffQuestionnairesSlugRouteWithChildren
  '/learn/$vertical/': typeof LearnVerticalIndexRoute
  '/staff/questionnaires/': typeof StaffQuestionnairesIndexRoute
  '/staff/questionnaires/$slug/': typeof StaffQuestionnairesSlugIndexRoute
  '/staff/questionnaires/$slug/versions/$versionId': typeof StaffQuestionnairesSlugVersionsVersionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consent': typeof ConsentRoute
  '/contact': typeof ContactRoute
  '/ed': typeof EdRoute
  '/ed-mints': typeof EdMintsRoute
  '/eligibility': typeof EligibilityRoute
  '/faq': typeof FaqRoute
  '/glp-1': typeof Glp1Route
  '/glp-1-houston': typeof Glp1HoustonRoute
  '/hair-loss': typeof HairLossRoute
  '/hair-loss-spray-men': typeof HairLossSprayMenRoute
  '/hair-loss-spray-women': typeof HairLossSprayWomenRoute
  '/how-it-works': typeof HowItWorksRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/nad-plus': typeof NadPlusRoute
  '/oral-finasteride': typeof OralFinasterideRoute
  '/oral-minoxidil-men': typeof OralMinoxidilMenRoute
  '/oral-minoxidil-women': typeof OralMinoxidilWomenRoute
  '/qualify': typeof QualifyRoute
  '/safety': typeof SafetyRoute
  '/semaglutide': typeof SemaglutideRoute
  '/sermorelin': typeof SermorelinRoute
  '/sexual-health': typeof SexualHealthRoute
  '/sildenafil': typeof SildenafilRoute
  '/submitted': typeof SubmittedRoute
  '/tadalafil': typeof TadalafilRoute
  '/tirzepatide': typeof TirzepatideRoute
  '/waitlist': typeof WaitlistRoute
  '/weight-loss': typeof WeightLossRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/intake': typeof DashboardIntakeRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/refills': typeof DashboardRefillsRoute
  '/learn/initial-research': typeof LearnInitialResearchRoute
  '/learn/resistance-training': typeof LearnResistanceTrainingRoute
  '/learn/rest-intervals': typeof LearnRestIntervalsRoute
  '/learn/semaglutide-vs-tirzepatide': typeof LearnSemaglutideVsTirzepatideRoute
  '/legal/hipaa': typeof LegalHipaaRoute
  '/legal/intake-acknowledgments': typeof LegalIntakeAcknowledgmentsRoute
  '/legal/physician-code-of-conduct': typeof LegalPhysicianCodeOfConductRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/shipping': typeof LegalShippingRoute
  '/legal/telehealth-consent': typeof LegalTelehealthConsentRoute
  '/legal/terms': typeof LegalTermsRoute
  '/lp/$slug': typeof LpSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/staff/analytics': typeof StaffAnalyticsRoute
  '/staff/dev': typeof StaffDevRoute
  '/staff/experiments': typeof StaffExperimentsRoute
  '/staff/landing-pages': typeof StaffLandingPagesRoute
  '/staff/medications': typeof StaffMedicationsRoute
  '/staff/patients': typeof StaffPatientsRoute
  '/staff/vendors': typeof StaffVendorsRoute
  '/verify-email/pending': typeof VerifyEmailPendingRoute
  '/dashboard': typeof DashboardIndexRoute
  '/learn': typeof LearnIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/staff': typeof StaffIndexRoute
  '/verify-email': typeof VerifyEmailIndexRoute
  '/learn/$vertical/$slug': typeof LearnVerticalSlugRoute
  '/learn/$vertical': typeof LearnVerticalIndexRoute
  '/staff/questionnaires': typeof StaffQuestionnairesIndexRoute
  '/staff/questionnaires/$slug': typeof StaffQuestionnairesSlugIndexRoute
  '/staff/questionnaires/$slug/versions/$versionId': typeof StaffQuestionnairesSlugVersionsVersionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consent': typeof ConsentRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/ed': typeof EdRoute
  '/ed-mints': typeof EdMintsRoute
  '/eligibility': typeof EligibilityRoute
  '/faq': typeof FaqRoute
  '/glp-1': typeof Glp1Route
  '/glp-1-houston': typeof Glp1HoustonRoute
  '/hair-loss': typeof HairLossRoute
  '/hair-loss-spray-men': typeof HairLossSprayMenRoute
  '/hair-loss-spray-women': typeof HairLossSprayWomenRoute
  '/how-it-works': typeof HowItWorksRoute
  '/intake': typeof IntakeRoute
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/nad-plus': typeof NadPlusRoute
  '/oral-finasteride': typeof OralFinasterideRoute
  '/oral-minoxidil-men': typeof OralMinoxidilMenRoute
  '/oral-minoxidil-women': typeof OralMinoxidilWomenRoute
  '/qualify': typeof QualifyRoute
  '/safety': typeof SafetyRoute
  '/semaglutide': typeof SemaglutideRoute
  '/sermorelin': typeof SermorelinRoute
  '/sexual-health': typeof SexualHealthRoute
  '/sildenafil': typeof SildenafilRoute
  '/staff': typeof StaffRouteWithChildren
  '/submitted': typeof SubmittedRoute
  '/tadalafil': typeof TadalafilRoute
  '/tirzepatide': typeof TirzepatideRoute
  '/verify-email': typeof VerifyEmailRouteWithChildren
  '/waitlist': typeof WaitlistRoute
  '/weight-loss': typeof WeightLossRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/intake': typeof DashboardIntakeRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/refills': typeof DashboardRefillsRoute
  '/learn/$vertical': typeof LearnVerticalRouteWithChildren
  '/learn/initial-research': typeof LearnInitialResearchRoute
  '/learn/resistance-training': typeof LearnResistanceTrainingRoute
  '/learn/rest-intervals': typeof LearnRestIntervalsRoute
  '/learn/semaglutide-vs-tirzepatide': typeof LearnSemaglutideVsTirzepatideRoute
  '/legal/hipaa': typeof LegalHipaaRoute
  '/legal/intake-acknowledgments': typeof LegalIntakeAcknowledgmentsRoute
  '/legal/physician-code-of-conduct': typeof LegalPhysicianCodeOfConductRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/shipping': typeof LegalShippingRoute
  '/legal/telehealth-consent': typeof LegalTelehealthConsentRoute
  '/legal/terms': typeof LegalTermsRoute
  '/lp/$slug': typeof LpSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/staff/analytics': typeof StaffAnalyticsRoute
  '/staff/dev': typeof StaffDevRoute
  '/staff/experiments': typeof StaffExperimentsRoute
  '/staff/landing-pages': typeof StaffLandingPagesRoute
  '/staff/medications': typeof StaffMedicationsRoute
  '/staff/patients': typeof StaffPatientsRoute
  '/staff/questionnaires': typeof StaffQuestionnairesRouteWithChildren
  '/staff/vendors': typeof StaffVendorsRoute
  '/verify-email/pending': typeof VerifyEmailPendingRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/verify-email/': typeof VerifyEmailIndexRoute
  '/learn/$vertical/$slug': typeof LearnVerticalSlugRoute
  '/staff/questionnaires/$slug': typeof StaffQuestionnairesSlugRouteWithChildren
  '/learn/$vertical/': typeof LearnVerticalIndexRoute
  '/staff/questionnaires/': typeof StaffQuestionnairesIndexRoute
  '/staff/questionnaires/$slug/': typeof StaffQuestionnairesSlugIndexRoute
  '/staff/questionnaires/$slug/versions/$versionId': typeof StaffQuestionnairesSlugVersionsVersionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/consent'
    | '/contact'
    | '/dashboard'
    | '/ed'
    | '/ed-mints'
    | '/eligibility'
    | '/faq'
    | '/glp-1'
    | '/glp-1-houston'
    | '/hair-loss'
    | '/hair-loss-spray-men'
    | '/hair-loss-spray-women'
    | '/how-it-works'
    | '/intake'
    | '/learn'
    | '/login'
    | '/nad-plus'
    | '/oral-finasteride'
    | '/oral-minoxidil-men'
    | '/oral-minoxidil-women'
    | '/qualify'
    | '/safety'
    | '/semaglutide'
    | '/sermorelin'
    | '/sexual-health'
    | '/sildenafil'
    | '/staff'
    | '/submitted'
    | '/tadalafil'
    | '/tirzepatide'
    | '/verify-email'
    | '/waitlist'
    | '/weight-loss'
    | '/dashboard/account'
    | '/dashboard/documents'
    | '/dashboard/intake'
    | '/dashboard/orders'
    | '/dashboard/refills'
    | '/learn/$vertical'
    | '/learn/initial-research'
    | '/learn/resistance-training'
    | '/learn/rest-intervals'
    | '/learn/semaglutide-vs-tirzepatide'
    | '/legal/hipaa'
    | '/legal/intake-acknowledgments'
    | '/legal/physician-code-of-conduct'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/shipping'
    | '/legal/telehealth-consent'
    | '/legal/terms'
    | '/lp/$slug'
    | '/recipes/$slug'
    | '/staff/analytics'
    | '/staff/dev'
    | '/staff/experiments'
    | '/staff/landing-pages'
    | '/staff/medications'
    | '/staff/patients'
    | '/staff/questionnaires'
    | '/staff/vendors'
    | '/verify-email/pending'
    | '/dashboard/'
    | '/learn/'
    | '/recipes/'
    | '/staff/'
    | '/verify-email/'
    | '/learn/$vertical/$slug'
    | '/staff/questionnaires/$slug'
    | '/learn/$vertical/'
    | '/staff/questionnaires/'
    | '/staff/questionnaires/$slug/'
    | '/staff/questionnaires/$slug/versions/$versionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/consent'
    | '/contact'
    | '/ed'
    | '/ed-mints'
    | '/eligibility'
    | '/faq'
    | '/glp-1'
    | '/glp-1-houston'
    | '/hair-loss'
    | '/hair-loss-spray-men'
    | '/hair-loss-spray-women'
    | '/how-it-works'
    | '/intake'
    | '/login'
    | '/nad-plus'
    | '/oral-finasteride'
    | '/oral-minoxidil-men'
    | '/oral-minoxidil-women'
    | '/qualify'
    | '/safety'
    | '/semaglutide'
    | '/sermorelin'
    | '/sexual-health'
    | '/sildenafil'
    | '/submitted'
    | '/tadalafil'
    | '/tirzepatide'
    | '/waitlist'
    | '/weight-loss'
    | '/dashboard/account'
    | '/dashboard/documents'
    | '/dashboard/intake'
    | '/dashboard/orders'
    | '/dashboard/refills'
    | '/learn/initial-research'
    | '/learn/resistance-training'
    | '/learn/rest-intervals'
    | '/learn/semaglutide-vs-tirzepatide'
    | '/legal/hipaa'
    | '/legal/intake-acknowledgments'
    | '/legal/physician-code-of-conduct'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/shipping'
    | '/legal/telehealth-consent'
    | '/legal/terms'
    | '/lp/$slug'
    | '/recipes/$slug'
    | '/staff/analytics'
    | '/staff/dev'
    | '/staff/experiments'
    | '/staff/landing-pages'
    | '/staff/medications'
    | '/staff/patients'
    | '/staff/vendors'
    | '/verify-email/pending'
    | '/dashboard'
    | '/learn'
    | '/recipes'
    | '/staff'
    | '/verify-email'
    | '/learn/$vertical/$slug'
    | '/learn/$vertical'
    | '/staff/questionnaires'
    | '/staff/questionnaires/$slug'
    | '/staff/questionnaires/$slug/versions/$versionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/consent'
    | '/contact'
    | '/dashboard'
    | '/ed'
    | '/ed-mints'
    | '/eligibility'
    | '/faq'
    | '/glp-1'
    | '/glp-1-houston'
    | '/hair-loss'
    | '/hair-loss-spray-men'
    | '/hair-loss-spray-women'
    | '/how-it-works'
    | '/intake'
    | '/learn'
    | '/login'
    | '/nad-plus'
    | '/oral-finasteride'
    | '/oral-minoxidil-men'
    | '/oral-minoxidil-women'
    | '/qualify'
    | '/safety'
    | '/semaglutide'
    | '/sermorelin'
    | '/sexual-health'
    | '/sildenafil'
    | '/staff'
    | '/submitted'
    | '/tadalafil'
    | '/tirzepatide'
    | '/verify-email'
    | '/waitlist'
    | '/weight-loss'
    | '/dashboard/account'
    | '/dashboard/documents'
    | '/dashboard/intake'
    | '/dashboard/orders'
    | '/dashboard/refills'
    | '/learn/$vertical'
    | '/learn/initial-research'
    | '/learn/resistance-training'
    | '/learn/rest-intervals'
    | '/learn/semaglutide-vs-tirzepatide'
    | '/legal/hipaa'
    | '/legal/intake-acknowledgments'
    | '/legal/physician-code-of-conduct'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/shipping'
    | '/legal/telehealth-consent'
    | '/legal/terms'
    | '/lp/$slug'
    | '/recipes/$slug'
    | '/staff/analytics'
    | '/staff/dev'
    | '/staff/experiments'
    | '/staff/landing-pages'
    | '/staff/medications'
    | '/staff/patients'
    | '/staff/questionnaires'
    | '/staff/vendors'
    | '/verify-email/pending'
    | '/dashboard/'
    | '/learn/'
    | '/recipes/'
    | '/staff/'
    | '/verify-email/'
    | '/learn/$vertical/$slug'
    | '/staff/questionnaires/$slug'
    | '/learn/$vertical/'
    | '/staff/questionnaires/'
    | '/staff/questionnaires/$slug/'
    | '/staff/questionnaires/$slug/versions/$versionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConsentRoute: typeof ConsentRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EdRoute: typeof EdRoute
  EdMintsRoute: typeof EdMintsRoute
  EligibilityRoute: typeof EligibilityRoute
  FaqRoute: typeof FaqRoute
  Glp1Route: typeof Glp1Route
  Glp1HoustonRoute: typeof Glp1HoustonRoute
  HairLossRoute: typeof HairLossRoute
  HairLossSprayMenRoute: typeof HairLossSprayMenRoute
  HairLossSprayWomenRoute: typeof HairLossSprayWomenRoute
  HowItWorksRoute: typeof HowItWorksRoute
  IntakeRoute: typeof IntakeRoute
  LearnRoute: typeof LearnRouteWithChildren
  LoginRoute: typeof LoginRoute
  NadPlusRoute: typeof NadPlusRoute
  OralFinasterideRoute: typeof OralFinasterideRoute
  OralMinoxidilMenRoute: typeof OralMinoxidilMenRoute
  OralMinoxidilWomenRoute: typeof OralMinoxidilWomenRoute
  QualifyRoute: typeof QualifyRoute
  SafetyRoute: typeof SafetyRoute
  SemaglutideRoute: typeof SemaglutideRoute
  SermorelinRoute: typeof SermorelinRoute
  SexualHealthRoute: typeof SexualHealthRoute
  SildenafilRoute: typeof SildenafilRoute
  StaffRoute: typeof StaffRouteWithChildren
  SubmittedRoute: typeof SubmittedRoute
  TadalafilRoute: typeof TadalafilRoute
  TirzepatideRoute: typeof TirzepatideRoute
  VerifyEmailRoute: typeof VerifyEmailRouteWithChildren
  WaitlistRoute: typeof WaitlistRoute
  WeightLossRoute: typeof WeightLossRoute
  LegalHipaaRoute: typeof LegalHipaaRoute
  LegalIntakeAcknowledgmentsRoute: typeof LegalIntakeAcknowledgmentsRoute
  LegalPhysicianCodeOfConductRoute: typeof LegalPhysicianCodeOfConductRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalShippingRoute: typeof LegalShippingRoute
  LegalTelehealthConsentRoute: typeof LegalTelehealthConsentRoute
  LegalTermsRoute: typeof LegalTermsRoute
  LpSlugRoute: typeof LpSlugRoute
  RecipesSlugRoute: typeof RecipesSlugRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weight-loss': {
      id: '/weight-loss'
      path: '/weight-loss'
      fullPath: '/weight-loss'
      preLoaderRoute: typeof WeightLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tirzepatide': {
      id: '/tirzepatide'
      path: '/tirzepatide'
      fullPath: '/tirzepatide'
      preLoaderRoute: typeof TirzepatideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tadalafil': {
      id: '/tadalafil'
      path: '/tadalafil'
      fullPath: '/tadalafil'
      preLoaderRoute: typeof TadalafilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submitted': {
      id: '/submitted'
      path: '/submitted'
      fullPath: '/submitted'
      preLoaderRoute: typeof SubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sildenafil': {
      id: '/sildenafil'
      path: '/sildenafil'
      fullPath: '/sildenafil'
      preLoaderRoute: typeof SildenafilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sexual-health': {
      id: '/sexual-health'
      path: '/sexual-health'
      fullPath: '/sexual-health'
      preLoaderRoute: typeof SexualHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sermorelin': {
      id: '/sermorelin'
      path: '/sermorelin'
      fullPath: '/sermorelin'
      preLoaderRoute: typeof SermorelinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semaglutide': {
      id: '/semaglutide'
      path: '/semaglutide'
      fullPath: '/semaglutide'
      preLoaderRoute: typeof SemaglutideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualify': {
      id: '/qualify'
      path: '/qualify'
      fullPath: '/qualify'
      preLoaderRoute: typeof QualifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oral-minoxidil-women': {
      id: '/oral-minoxidil-women'
      path: '/oral-minoxidil-women'
      fullPath: '/oral-minoxidil-women'
      preLoaderRoute: typeof OralMinoxidilWomenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oral-minoxidil-men': {
      id: '/oral-minoxidil-men'
      path: '/oral-minoxidil-men'
      fullPath: '/oral-minoxidil-men'
      preLoaderRoute: typeof OralMinoxidilMenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oral-finasteride': {
      id: '/oral-finasteride'
      path: '/oral-finasteride'
      fullPath: '/oral-finasteride'
      preLoaderRoute: typeof OralFinasterideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nad-plus': {
      id: '/nad-plus'
      path: '/nad-plus'
      fullPath: '/nad-plus'
      preLoaderRoute: typeof NadPlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hair-loss-spray-women': {
      id: '/hair-loss-spray-women'
      path: '/hair-loss-spray-women'
      fullPath: '/hair-loss-spray-women'
      preLoaderRoute: typeof HairLossSprayWomenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hair-loss-spray-men': {
      id: '/hair-loss-spray-men'
      path: '/hair-loss-spray-men'
      fullPath: '/hair-loss-spray-men'
      preLoaderRoute: typeof HairLossSprayMenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hair-loss': {
      id: '/hair-loss'
      path: '/hair-loss'
      fullPath: '/hair-loss'
      preLoaderRoute: typeof HairLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glp-1-houston': {
      id: '/glp-1-houston'
      path: '/glp-1-houston'
      fullPath: '/glp-1-houston'
      preLoaderRoute: typeof Glp1HoustonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glp-1': {
      id: '/glp-1'
      path: '/glp-1'
      fullPath: '/glp-1'
      preLoaderRoute: typeof Glp1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ed-mints': {
      id: '/ed-mints'
      path: '/ed-mints'
      fullPath: '/ed-mints'
      preLoaderRoute: typeof EdMintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ed': {
      id: '/ed'
      path: '/ed'
      fullPath: '/ed'
      preLoaderRoute: typeof EdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email/': {
      id: '/verify-email/'
      path: '/'
      fullPath: '/verify-email/'
      preLoaderRoute: typeof VerifyEmailIndexRouteImport
      parentRoute: typeof VerifyEmailRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/verify-email/pending': {
      id: '/verify-email/pending'
      path: '/pending'
      fullPath: '/verify-email/pending'
      preLoaderRoute: typeof VerifyEmailPendingRouteImport
      parentRoute: typeof VerifyEmailRoute
    }
    '/staff/vendors': {
      id: '/staff/vendors'
      path: '/vendors'
      fullPath: '/staff/vendors'
      preLoaderRoute: typeof StaffVendorsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/questionnaires': {
      id: '/staff/questionnaires'
      path: '/questionnaires'
      fullPath: '/staff/questionnaires'
      preLoaderRoute: typeof StaffQuestionnairesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/patients': {
      id: '/staff/patients'
      path: '/patients'
      fullPath: '/staff/patients'
      preLoaderRoute: typeof StaffPatientsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/medications': {
      id: '/staff/medications'
      path: '/medications'
      fullPath: '/staff/medications'
      preLoaderRoute: typeof StaffMedicationsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/landing-pages': {
      id: '/staff/landing-pages'
      path: '/landing-pages'
      fullPath: '/staff/landing-pages'
      preLoaderRoute: typeof StaffLandingPagesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/experiments': {
      id: '/staff/experiments'
      path: '/experiments'
      fullPath: '/staff/experiments'
      preLoaderRoute: typeof StaffExperimentsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/dev': {
      id: '/staff/dev'
      path: '/dev'
      fullPath: '/staff/dev'
      preLoaderRoute: typeof StaffDevRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/analytics': {
      id: '/staff/analytics'
      path: '/analytics'
      fullPath: '/staff/analytics'
      preLoaderRoute: typeof StaffAnalyticsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/recipes/$slug': {
      id: '/recipes/$slug'
      path: '/recipes/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/$slug': {
      id: '/lp/$slug'
      path: '/lp/$slug'
      fullPath: '/lp/$slug'
      preLoaderRoute: typeof LpSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/telehealth-consent': {
      id: '/legal/telehealth-consent'
      path: '/legal/telehealth-consent'
      fullPath: '/legal/telehealth-consent'
      preLoaderRoute: typeof LegalTelehealthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/shipping': {
      id: '/legal/shipping'
      path: '/legal/shipping'
      fullPath: '/legal/shipping'
      preLoaderRoute: typeof LegalShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/legal/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/physician-code-of-conduct': {
      id: '/legal/physician-code-of-conduct'
      path: '/legal/physician-code-of-conduct'
      fullPath: '/legal/physician-code-of-conduct'
      preLoaderRoute: typeof LegalPhysicianCodeOfConductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/intake-acknowledgments': {
      id: '/legal/intake-acknowledgments'
      path: '/legal/intake-acknowledgments'
      fullPath: '/legal/intake-acknowledgments'
      preLoaderRoute: typeof LegalIntakeAcknowledgmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/hipaa': {
      id: '/legal/hipaa'
      path: '/legal/hipaa'
      fullPath: '/legal/hipaa'
      preLoaderRoute: typeof LegalHipaaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/semaglutide-vs-tirzepatide': {
      id: '/learn/semaglutide-vs-tirzepatide'
      path: '/semaglutide-vs-tirzepatide'
      fullPath: '/learn/semaglutide-vs-tirzepatide'
      preLoaderRoute: typeof LearnSemaglutideVsTirzepatideRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/rest-intervals': {
      id: '/learn/rest-intervals'
      path: '/rest-intervals'
      fullPath: '/learn/rest-intervals'
      preLoaderRoute: typeof LearnRestIntervalsRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/resistance-training': {
      id: '/learn/resistance-training'
      path: '/resistance-training'
      fullPath: '/learn/resistance-training'
      preLoaderRoute: typeof LearnResistanceTrainingRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/initial-research': {
      id: '/learn/initial-research'
      path: '/initial-research'
      fullPath: '/learn/initial-research'
      preLoaderRoute: typeof LearnInitialResearchRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/$vertical': {
      id: '/learn/$vertical'
      path: '/$vertical'
      fullPath: '/learn/$vertical'
      preLoaderRoute: typeof LearnVerticalRouteImport
      parentRoute: typeof LearnRoute
    }
    '/dashboard/refills': {
      id: '/dashboard/refills'
      path: '/refills'
      fullPath: '/dashboard/refills'
      preLoaderRoute: typeof DashboardRefillsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/intake': {
      id: '/dashboard/intake'
      path: '/intake'
      fullPath: '/dashboard/intake'
      preLoaderRoute: typeof DashboardIntakeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/staff/questionnaires/': {
      id: '/staff/questionnaires/'
      path: '/'
      fullPath: '/staff/questionnaires/'
      preLoaderRoute: typeof StaffQuestionnairesIndexRouteImport
      parentRoute: typeof StaffQuestionnairesRoute
    }
    '/learn/$vertical/': {
      id: '/learn/$vertical/'
      path: '/'
      fullPath: '/learn/$vertical/'
      preLoaderRoute: typeof LearnVerticalIndexRouteImport
      parentRoute: typeof LearnVerticalRoute
    }
    '/staff/questionnaires/$slug': {
      id: '/staff/questionnaires/$slug'
      path: '/$slug'
      fullPath: '/staff/questionnaires/$slug'
      preLoaderRoute: typeof StaffQuestionnairesSlugRouteImport
      parentRoute: typeof StaffQuestionnairesRoute
    }
    '/learn/$vertical/$slug': {
      id: '/learn/$vertical/$slug'
      path: '/$slug'
      fullPath: '/learn/$vertical/$slug'
      preLoaderRoute: typeof LearnVerticalSlugRouteImport
      parentRoute: typeof LearnVerticalRoute
    }
    '/staff/questionnaires/$slug/': {
      id: '/staff/questionnaires/$slug/'
      path: '/'
      fullPath: '/staff/questionnaires/$slug/'
      preLoaderRoute: typeof StaffQuestionnairesSlugIndexRouteImport
      parentRoute: typeof StaffQuestionnairesSlugRoute
    }
    '/staff/questionnaires/$slug/versions/$versionId': {
      id: '/staff/questionnaires/$slug/versions/$versionId'
      path: '/versions/$versionId'
      fullPath: '/staff/questionnaires/$slug/versions/$versionId'
      preLoaderRoute: typeof StaffQuestionnairesSlugVersionsVersionIdRouteImport
      parentRoute: typeof StaffQuestionnairesSlugRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardIntakeRoute: typeof DashboardIntakeRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardRefillsRoute: typeof DashboardRefillsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardIntakeRoute: DashboardIntakeRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardRefillsRoute: DashboardRefillsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface LearnVerticalRouteChildren {
  LearnVerticalSlugRoute: typeof LearnVerticalSlugRoute
  LearnVerticalIndexRoute: typeof LearnVerticalIndexRoute
}

const LearnVerticalRouteChildren: LearnVerticalRouteChildren = {
  LearnVerticalSlugRoute: LearnVerticalSlugRoute,
  LearnVerticalIndexRoute: LearnVerticalIndexRoute,
}

const LearnVerticalRouteWithChildren = LearnVerticalRoute._addFileChildren(
  LearnVerticalRouteChildren,
)

interface LearnRouteChildren {
  LearnVerticalRoute: typeof LearnVerticalRouteWithChildren
  LearnInitialResearchRoute: typeof LearnInitialResearchRoute
  LearnResistanceTrainingRoute: typeof LearnResistanceTrainingRoute
  LearnRestIntervalsRoute: typeof LearnRestIntervalsRoute
  LearnSemaglutideVsTirzepatideRoute: typeof LearnSemaglutideVsTirzepatideRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnVerticalRoute: LearnVerticalRouteWithChildren,
  LearnInitialResearchRoute: LearnInitialResearchRoute,
  LearnResistanceTrainingRoute: LearnResistanceTrainingRoute,
  LearnRestIntervalsRoute: LearnRestIntervalsRoute,
  LearnSemaglutideVsTirzepatideRoute: LearnSemaglutideVsTirzepatideRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface StaffQuestionnairesSlugRouteChildren {
  StaffQuestionnairesSlugIndexRoute: typeof StaffQuestionnairesSlugIndexRoute
  StaffQuestionnairesSlugVersionsVersionIdRoute: typeof StaffQuestionnairesSlugVersionsVersionIdRoute
}

const StaffQuestionnairesSlugRouteChildren: StaffQuestionnairesSlugRouteChildren =
  {
    StaffQuestionnairesSlugIndexRoute: StaffQuestionnairesSlugIndexRoute,
    StaffQuestionnairesSlugVersionsVersionIdRoute:
      StaffQuestionnairesSlugVersionsVersionIdRoute,
  }

const StaffQuestionnairesSlugRouteWithChildren =
  StaffQuestionnairesSlugRoute._addFileChildren(
    StaffQuestionnairesSlugRouteChildren,
  )

interface StaffQuestionnairesRouteChildren {
  StaffQuestionnairesSlugRoute: typeof StaffQuestionnairesSlugRouteWithChildren
  StaffQuestionnairesIndexRoute: typeof StaffQuestionnairesIndexRoute
}

const StaffQuestionnairesRouteChildren: StaffQuestionnairesRouteChildren = {
  StaffQuestionnairesSlugRoute: StaffQuestionnairesSlugRouteWithChildren,
  StaffQuestionnairesIndexRoute: StaffQuestionnairesIndexRoute,
}

const StaffQuestionnairesRouteWithChildren =
  StaffQuestionnairesRoute._addFileChildren(StaffQuestionnairesRouteChildren)

interface StaffRouteChildren {
  StaffAnalyticsRoute: typeof StaffAnalyticsRoute
  StaffDevRoute: typeof StaffDevRoute
  StaffExperimentsRoute: typeof StaffExperimentsRoute
  StaffLandingPagesRoute: typeof StaffLandingPagesRoute
  StaffMedicationsRoute: typeof StaffMedicationsRoute
  StaffPatientsRoute: typeof StaffPatientsRoute
  StaffQuestionnairesRoute: typeof StaffQuestionnairesRouteWithChildren
  StaffVendorsRoute: typeof StaffVendorsRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAnalyticsRoute: StaffAnalyticsRoute,
  StaffDevRoute: StaffDevRoute,
  StaffExperimentsRoute: StaffExperimentsRoute,
  StaffLandingPagesRoute: StaffLandingPagesRoute,
  StaffMedicationsRoute: StaffMedicationsRoute,
  StaffPatientsRoute: StaffPatientsRoute,
  StaffQuestionnairesRoute: StaffQuestionnairesRouteWithChildren,
  StaffVendorsRoute: StaffVendorsRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface VerifyEmailRouteChildren {
  VerifyEmailPendingRoute: typeof VerifyEmailPendingRoute
  VerifyEmailIndexRoute: typeof VerifyEmailIndexRoute
}

const VerifyEmailRouteChildren: VerifyEmailRouteChildren = {
  VerifyEmailPendingRoute: VerifyEmailPendingRoute,
  VerifyEmailIndexRoute: VerifyEmailIndexRoute,
}

const VerifyEmailRouteWithChildren = VerifyEmailRoute._addFileChildren(
  VerifyEmailRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConsentRoute: ConsentRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EdRoute: EdRoute,
  EdMintsRoute: EdMintsRoute,
  EligibilityRoute: EligibilityRoute,
  FaqRoute: FaqRoute,
  Glp1Route: Glp1Route,
  Glp1HoustonRoute: Glp1HoustonRoute,
  HairLossRoute: HairLossRoute,
  HairLossSprayMenRoute: HairLossSprayMenRoute,
  HairLossSprayWomenRoute: HairLossSprayWomenRoute,
  HowItWorksRoute: HowItWorksRoute,
  IntakeRoute: IntakeRoute,
  LearnRoute: LearnRouteWithChildren,
  LoginRoute: LoginRoute,
  NadPlusRoute: NadPlusRoute,
  OralFinasterideRoute: OralFinasterideRoute,
  OralMinoxidilMenRoute: OralMinoxidilMenRoute,
  OralMinoxidilWomenRoute: OralMinoxidilWomenRoute,
  QualifyRoute: QualifyRoute,
  SafetyRoute: SafetyRoute,
  SemaglutideRoute: SemaglutideRoute,
  SermorelinRoute: SermorelinRoute,
  SexualHealthRoute: SexualHealthRoute,
  SildenafilRoute: SildenafilRoute,
  StaffRoute: StaffRouteWithChildren,
  SubmittedRoute: SubmittedRoute,
  TadalafilRoute: TadalafilRoute,
  TirzepatideRoute: TirzepatideRoute,
  VerifyEmailRoute: VerifyEmailRouteWithChildren,
  WaitlistRoute: WaitlistRoute,
  WeightLossRoute: WeightLossRoute,
  LegalHipaaRoute: LegalHipaaRoute,
  LegalIntakeAcknowledgmentsRoute: LegalIntakeAcknowledgmentsRoute,
  LegalPhysicianCodeOfConductRoute: LegalPhysicianCodeOfConductRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalShippingRoute: LegalShippingRoute,
  LegalTelehealthConsentRoute: LegalTelehealthConsentRoute,
  LegalTermsRoute: LegalTermsRoute,
  LpSlugRoute: LpSlugRoute,
  RecipesSlugRoute: RecipesSlugRoute,
  RecipesIndexRoute: RecipesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
